eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
server:
  port: 9005
spring:
  application:
    name: zuul-server
  zipkin:
      base-url: http://localhost:9008
  sleuth:
    sampler:
      percentage: 1.0
zuul:
  routes:
    adi-admin:
      path: /api/admin/**
      serviceId: admin-app
    api-client:
      path: /api/client/**
      serviceId: client-app