eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
server:
  port: 9012
spring:
  application:
    name: client-app
  zipkin:
      base-url: http://localhost:9008
  sleuth:
    sampler:
      percentage: 1.0
feign:
  hystrix:
    enabled: true
management:
  security:
    enabled: false