eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
server:
  port: 9012
spring:
  application:
    name: client-app
feign:
  hystrix:
    enabled: true
management:
  security:
    enabled: false


