eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
server:
  port: 9006
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: http://localhost:3000/kyy/spring-cloud-demo.git
          search-paths: config-server/src/main/resources/config
      label: master